# Configure main menu and social menu
[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
    [main.params]
        icon = "home"
        newtab = false

[[main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 20
    [main.params]
        icon = "categories"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30
    [main.params]
        icon = "archives"

[[main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 40
    [main.params]
        icon = "tag"

[[main]]
    identifier = "links"
    name = "友链"
    url = "/links/"
    weight = 50
    [main.params]
        icon = "link"

[[main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 70
    [main.params]
        icon = "user"



[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/CaiJimmy/hugo-theme-stack"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "email"
    name       = "邮件"
    url        = "mailto:han_gr@foxmail.com"

    [social.params]
        icon = "mail"
